name: Prettier codes

on:
  workflow_run:
    workflows:
      - Build codes
    types:
      - completed

env:
  node-version: lts/*

jobs:
  run-formatter:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
    steps:
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Get yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Format with eslint
        run: yarn run lint:fix
      - name: Format the code
        run: yarn run fmt
      - name: Auto commit
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "fix(front): auto-fixable format by github-actions"; \
            git push origin HEAD:${GITHUB_REF}; \
          fi
